[workers]


worker-1 ansible_host=18.212.223.203


worker-2 ansible_host=98.89.32.73


worker-3 ansible_host=34.228.153.255


worker-4 ansible_host=54.82.14.49


worker-5 ansible_host=54.172.213.169

 
[workers:vars]

ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/Backup_key.pem
ansible_python_interpreter=/usr/bin/python3